# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
references:
  container: &container
    docker:
      - image: circleci/python:2.7.13
      - name: localstack
        image: localstack/localstack
    working_directory: ~/repo

jobs:
  build:
    <<: *container
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}-{{ checksum "requirements-dev.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            pip install virtualenv
            virtualenv venv
            . venv/bin/activate
            pip install -r requirements.txt
            pip install -r requirements-dev.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}-{{ checksum "requirements-dev.txt" }}
        
      - run:
          name: run tests
          environment:
            LOCALSTACK_HOST: localstack
          command: |
            . venv/bin/activate
            CUMULUS_ENV=testing nosetests -v -s
  release:
    <<: *container
    steps:
      - run:
          name: Push tag to github
          command: |
            ls
            mkdir -p ~/.ssh
            ssh-keyscan github.com >> ~/.ssh/known_hosts
            VERSION=`awk -F\' '{print $2,$4}' message_adapter/version.py`
            git tag $VERSION
            git push origin $VERSION

workflows:
  version: 2
  build_test_release:
    jobs:
      - build
      - release:
          requires:
            - build
          filters:
            branches:
              only: abarciauskas-bgse_ci-build-release
